version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: sliitek_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - sliitek_net

  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/sliitek-backend:latest
    container_name: sliitek_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - redis
    networks:
      - sliitek_net

  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/sliitek-frontend:latest
    container_name: sliitek_frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - sliitek_net

networks:
  sliitek_net:
    driver: bridge

